To-do:
- Show people how to navigate to Nexctcloud through browser, and how to get the app.
- - How to navigate between Talk and Folders.
- How to recieve an account from the admin
- - How to make an account for others if you are the admin
- - - Extra details about storage quotas, groups, etc
- - Note about how you don't make an account online
- How to log in
- - How to connect a PC to a server
- - How to connect a mobile to a server
- How to make new folders and files
- - How to upload files
- - How to share files
- How syncing works
- Detailed and **simple** troubleshooting
